---
kind: pipeline
type: docker
name: compile-pipeline-yarn

concurrency:
  limit: 1

platform:
  os: linux
  arch: amd64

steps:

  - name: restore-cache
    image: meltwater/drone-cache:dev
    settings:
      access_key: 
        from_secret: access_key
      secret_key: 
        from_secret: secret_key
      restore: true
      bucket: boom-drone-demo
      region: eu-west-1
      mount:
        - "/drone/src/node_modules"
        - "/drone/src/ui-boom-components/node_modules"
        - "/drone/src/platform/node_modules"
        - "/drone/src/platform-guest/node_modules"

  - name: compile-with-yarn
    image: node:12-alpine3.10
    commands:
      - yarn

#  - name: rebuild-cache
#    image: meltwater/drone-cache:dev
#    settings:
#      access_key: 
#        from_secret: access_key
#      secret_key: 
#        from_secret: secret_key
#      rebuild: true
#      bucket: boom-drone-demo
#      region: eu-west-1
#      mount:
#        - "/drone/src/node_modules"
#        - "/drone/src/ui-boom-components/node_modules"
#        - "/drone/src/platform/node_modules"
#        - "/drone/src/platform-guest/node_modules"
#    when:
#      status:
#      - failure      
#      - success      


  - name: test-with-yarn
    image: aaa/allure-node
    pull: never
    commands:
      - sleep 3600
    #commands:
      #- yarn workspaces run test
      #- npm install --save-dev jest-allure      
      #- sleep 3600
    environment:
      CI: "true"
      REACT_APP_API_BASE_URL: http://localhost:8080
      REACT_APP_API_VERSION: v1

  #- name: debug
  #  image: alpine  
  #  commands:
  #    - sleep 3600
  #  when:
  #    status:
  #    - failure      
  #    - success



trigger:
  branch:
    - master
    - develop
  event:
    - push

