import { ParseResult } from 'papaparse';
import { errors, Row, validateParsedResult } from './utils';

describe('ShootingBulkUploadView utils', () => {
  describe('validateParsedResult', () => {
    it('should validate parsed result with no errors', () => {
      const parsed = {
        data: [
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '30/03/2020',
            'Start Time': '14:30',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Marco Rossi',
            'Phone number': '+393401212124',
            Email: 'marco@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '',
            'Start Time': '',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste Rossi',
            'Phone number': '+39340121212434',
            Email: 'ste@boom.com',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '26/04/2020',
            'Start Time': '14:30',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste Rossi',
            'Phone number': '+39340121212434',
            Email: 'ste@boom.com',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '27/04/2020',
            'Start Time': '14:30',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '28/04/2020',
            'Start Time': '14:30',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '',
            'Start Time': '',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'SweetGuest',
            Company: 'SweetGuest',
            Package: 'Prova Ste',
            'Start Date': '30/04/2020',
            'Start Time': '14:30',
            Address: 'Via privata Gerolamo Avogadro, 6, Milano, Italy, 20143',
            Title: 'Sample shooting',
            Description: 'Sample description',
            'Logistic Information': 'logistic 1',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
        ],
        errors: [],
        meta: {},
      };

      expect(validateParsedResult((parsed as unknown) as ParseResult<Row>)).toEqual([]);
    });

    it('should return 5 errors', () => {
      const parsed = {
        data: [
          {
            Organization: 'My Org',
            Company: 'My Company',
            Package: 'Package Gold',
            'Start Date': '13/03/2020',
            'Start Time': '10:30',
            Address: 'Via R. Sanzio, 22, Venice, Italy, 22990',
            Title: 'Bau',
            Description: 'Sample description',
            '': 'logistic 1',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: '',
            Company: 'My cool Company',
            Package: 'Package Silver',
            'Start Date': '14/12/2020',
            'Start Time': '26:50',
            Address: 'Via Tal Dei Tali, 3, Venice, Italy, 22990',
            Title: 'Miao shoot',
            Description: 'Sample description',
            'Logistic Information': 'logistic 2',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 2',
            Company: 'Ciaone company',
            Package: 'Ciaone package',
            'Start Date': '15/09/2020',
            'Start Time': '11:30',
            Address: 'Via Avogadro, 5, Venice, Italy, 22990',
            Title: '',
            Description: 'Sample description',
            'Logistic Information': '',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 3',
            Company: 'Miao company',
            Package: 'Cool package',
            'Start Date': '13/06/2020',
            'Start Time': '09:30',
            Address: 'Via x',
            Title: 'Hello!',
            Description: 'Sample description',
            'Logistic Information': 'logistic 4',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 4',
            Company: 'Rofl company',
            Package: 'Hello there!',
            'Start Date': '23/13/2020',
            'Start Time': '18:30',
            Address: 'Via Faraday, 33, Milan, Italy, 20000',
            Title: '',
            Description: 'Sample description',
            'Logistic Information': 'logistic 5',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 5',
            Company: 'Lol company',
            Package: 'Package Eurospin',
            'Start Date': '12.04.2020',
            'Start Time': '25:30',
            Address: 'Via Di Vittorio, 4, Turin, Italy, 12345',
            Title: 'Shooting N',
            Description: 'Sample description',
            'Logistic Information': 'logistic 6',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 5',
            Company: 'Lol company',
            Package: 'Package Eurospin',
            'Start Date': '13/06/2020',
            'Start Time': '09:30',
            Address: 'Via Di Vittorio, 4, Turin, Italy, 12345',
            Title: '',
            Description: '',
            'Logistic Information': '',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 5',
            Company: 'Lol company',
            Package: 'Package Eurospin',
            'Start Date': '13/06/2020',
            'Start Time': '09:30',
            Address: 'Via Di Vittorio, 4, Turin, Italy, 12345',
            Title: '',
            Description: '',
            'Logistic Information': '',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom',
            'Business name': 'My business',
            'Multidelivery Emails': '',
          },
          {
            Organization: 'My Org 5',
            Company: 'Lol company',
            Package: 'Package Eurospin',
            'Start Date': '',
            'Start Time': '09:30',
            Address: 'Via Di Vittorio, 4, Turin, Italy, 12345',
            Title: '',
            Description: '',
            'Logistic Information': '',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom',
            'Business name': 'My business',
            'Multidelivery Emails': 'wrongmail.it',
          },
          {
            Organization: 'My Org 5',
            Company: 'Lol company',
            Package: 'Package Eurospin',
            'Start Date': '13/06/2020',
            'Start Time': '09:30',
            Address: 'Via Di Vittorio, 4, Turin, Italy, 12345',
            Title: '',
            Description: '',
            'Logistic Information': '',
            'Full name': 'Ste',
            'Phone number': '+393401212434',
            Email: 'ste@boom.co',
            'Business name': 'My business',
            'Multidelivery Emails': 'wrongmail.it;prova@email.co',
          },
        ],
        errors: [],
      };

      const expectedErrors = [
        {
          lineNumber: 2,
          error: errors.EMPTY_FIELDS,
        },
        {
          lineNumber: 5,
          error: errors.WRONG_DATE_FORMAT,
        },
        {
          lineNumber: 6,
          error: `${errors.WRONG_DATE_FORMAT}, ${errors.WRONG_TIME_FORMAT}`,
        },
        {
          lineNumber: 8,
          error: errors.WRONG_EMAIL,
        },
        {
          lineNumber: 9,
          error: errors.MISSING_DATE,
        },
        {
          lineNumber: 10,
          error: errors.WRONG_DELIVERY_EMAILS,
        },
      ];

      expect(validateParsedResult((parsed as unknown) as ParseResult<Row>)).toEqual(expectedErrors);
    });
  });
});
