//
// ──────────────────────────────────────────────────────────────────────────────────── I ──────────
//   :::::: C O M P A N I E S   A C T I O N   T Y P E S : :  :   :    :     :        :          :
// ──────────────────────────────────────────────────────────────────────────────────────────────
//

module.exports = {
  SAVE_COMPANIES: 'SAVE_COMPANIES',
  APPEND_COMPANIES: 'APPEND_COMPANIES',
  SAVE_COMPANIES_PAGINATION: 'SAVE_COMPANIES_PAGINATION',
  SET_COMPANIES_FILTER: 'SET_COMPANIES_FILTER',
  RESET_COMPANIES_FILTERS: 'RESET_COMPANIES_FILTERS',
  SET_COMPANY_ORGANIZATION: 'SET_COMPANY_ORGANIZATION',
  SET_SELECTED_COMPANY: 'SET_SELECTED_COMPANY',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  RESET_COMPANIES_DATA: 'RESET_COMPANIES_DATA',
  SAVE_FIRST_LEVEL_COMPANIES: 'SAVE_FIRST_LEVEL_COMPANIES',
  SAVE_ROOT_COMPANIES: 'SAVE_ROOT_COMPANIES',
  SAVE_ROOT_COMPANIES_PAGINATION: 'SAVE_ROOT_COMPANIES_PAGINATION',
  APPEND_ROOT_COMPANIES: 'APPEND_ROOT_COMPANIES',
  RESET_ROOT_COMPANIES: 'RESET_ROOT_COMPANIES',
  ADD_NEW_NAVIGATION_LEVEL: 'ADD_NEW_NAVIGATION_LEVEL',
  ADD_NEW_NAVIGATION_LEVELS: 'ADD_NEW_NAVIGATION_LEVELS',
  JUMP_NAVIGATION_LEVEL: 'JUMP_NAVIGATION_LEVEL',
  SET_SELECTED_ROOT_COMPANY: 'SET_SELECTED_ROOT_COMPANY',
  UPDATE_SELECTED_ROOT_COMPANY: 'UPDATE_SELECTED_ROOT_COMPANY',
  SAVE_SUB_COMPANIES: 'SAVE_SUB_COMPANIES',
  SAVE_SUB_COMPANIES_PAGINATION: 'SAVE_SUB_COMPANIES_PAGINATION',
  APPEND_SUB_COMPANIES: 'APPEND_SUB_COMPANIES',
  RESET_SUB_COMPANIES: 'RESET_SUB_COMPANIES',
  UPDATE_SUB_COMPANY: 'UPDATE_SUB_COMPANY',
  SET_SUB_COMPANY_FILTER: 'SET_SUB_COMPANY_FILTER',
  RESET_SUB_COMPANIES_FILTER: 'RESET_SUB_COMPANIES_FILTER',
  SET_ROOT_COMPANIES_FILTER: 'SET_ROOT_COMPANIES_FILTER',
  RESET_ROOT_COMPANIES_FILTERS: 'RESET_ROOT_COMPANIES_FILTERS',
  SAVE_COMPANY_PRICING_PACKAGES: 'SAVE_COMPANY_PRICING_PACKAGES',
  RESET_COMPANY_PRICING_PACKAGES: 'RESET_COMPANY_PRICING_PACKAGES',
  REPLACE_NAVIGATION_LEVEL: 'REPLACE_NAVIGATION_LEVEL',
  SAVE_COMPANY_CHECKLIST: 'SAVE_COMPANY_CHECKLIST',
  RESET_COMPANY_CHECKLIST: 'RESET_COMPANY_CHECKLIST',
};
