//
// ────────────────────────────────────────────────────────────────────────────────────────── I ──────────
//   :::::: O R G A N I Z A T I O N   A C T I O N   T Y P E S : :  :   :    :     :        :          :
// ────────────────────────────────────────────────────────────────────────────────────────────────────
//

module.exports = {
  SAVE_ORGANIZATIONS: 'SAVE_ORGANIZATIONS',
  DELETE_ORGANIZATION: 'DELETE_ORGANIZATION',
  SAVE_ORGANIZATIONS_PAGINATION: 'SAVE_ORGANIZATIONS_PAGINATION',
  SET_ORGANIZATIONS_FILTER: 'SET_ORGANIZATIONS_FILTER',
  RESET_ORGANIZATIONS_FILTERS: 'RESET_ORGANIZATIONS_FILTERS',
  SET_SELECTED_ORGANIZATION: 'SET_SELECTED_ORGANIZATION',
  APPEND_ORGANIZATIONS: 'APPEND_ORGANIZATIONS',
  SAVE_PRICING_PACKAGES: 'SAVE_PRICING_PACKAGES',
  APPEND_PRICING_PACKAGES: 'APPEND_PRICING_PACKAGES',
  SAVE_PRICING_PACKAGES_PAGINATION: 'SAVE_PRICING_PACKAGES_PAGINATION',
  SET_SELECTED_PRICING_PACKAGE: 'SET_SELECTED_PRICING_PACKAGE',
  RESET_PRICING_PACKAGES_DATA: 'RESET_PRICING_PACKAGES_DATA',
  SET_PRICING_PACKAGES_FILTER: 'SET_PRICING_PACKAGES_FILTER',
  RESET_PRICING_PACKAGES_FILTERS: 'RESET_PRICING_PACKAGES_FILTERS',
  SAVE_ORGANIZATION_AUTH_SERVICE: 'SAVE_ORGANIZATION_AUTH_SERVICE',
  RESET_ORGANIZATION_AUTH_SERVICE: 'RESET_ORGANIZATION_AUTH_SERVICE',
  UPDATE_SELECTED_ORGANIZATION: 'UPDATE_SELECTED_ORGANIZATION',
};
