//
// ────────────────────────────────────────────────────────────────────────────────────────── I ──────────
//   :::::: P H O T O G R A P H E R   A C T I O N   T Y P E S : :  :   :    :     :        :          :
// ────────────────────────────────────────────────────────────────────────────────────────────────────
//

module.exports = {
  SAVE_PHOTOGRAPHERS: 'SAVE_PHOTOGRAPHERS',
  APPEND_PHOTOGRAPHERS: 'APPEND_PHOTOGRAPHERS',
  SAVE_PHOTOGRAPHERS_PAGINATION: 'SAVE_PHOTOGRAPHERS_PAGINATION',
  SET_PHOTOGRAPHERS_FILTER: 'SET_PHOTOGRAPHERS_FILTER',
  SET_PHOTOGRAPHERS_FILTER_BLOCK: 'SET_PHOTOGRAPHERS_FILTER_BLOCK',
  RESET_PHOTOGRAPHERS_FILTERS: 'RESET_PHOTOGRAPHERS_FILTERS',
  DELETE_PHOTOGRAPHER: 'DELETE_PHOTOGRAPHER',
  RESET_PHOTOGRAPHERS_DATA: 'RESET_PHOTOGRAPHERS_DATA',
  UPDATE_PHOTOGRAPHER: 'UPDATE_PHOTOGRAPHER',
  SET_SELECTED_PHOTOGRAPHER: 'SET_SELECTED_PHOTOGRAPHER',
};
