//
// ──────────────────────────────────────────────────────────────────────────────────── I ──────────
//   :::::: S H O O T I N G S   A C T I O N   T Y P E S : :  :   :    :     :        :          :
// ──────────────────────────────────────────────────────────────────────────────────────────────
//

module.exports = {
  SAVE_SHOOTINGS: 'SAVE_SHOOTINGS',
  SAVE_CALENDAR_SHOOTINGS: 'SAVE_CALENDAR_SHOOTINGS',
  APPEND_SHOOTINGS: 'APPEND_SHOOTINGS',
  SAVE_SHOOTINGS_PAGINATION: 'SAVE_SHOOTINGS_PAGINATION',
  SET_SELECTED_SHOOTING: 'SET_SELECTED_SHOOTING',
  SET_SHOOTING_FILTER: 'SET_SHOOTING_FILTER',
  RESET_SHOOTING_FILTERS: 'RESET_SHOOTING_FILTERS',
  UPDATE_SHOOTING: 'UPDATE_SHOOTING',
  RESET_SHOOTINGS_DATA: 'RESET_SHOOTINGS_DATA',
  DELETE_SHOOTING: 'DELETE_SHOOTING',
  SET_SHOOTING_FILTER_BLOCK: 'SET_SHOOTING_FILTER_BLOCK',
  SAVE_DAILY_SHOOTINGS: 'SAVE_DAILY_SHOOTINGS',
  RESET_DAILY_SHOOTINGS: 'RESET_DAILY_SHOOTINGS',
  SET_DAILY_SHOOTING_FILTER: 'SET_DAILY_SHOOTING_FILTER',
  RESET_DAILY_SHOOTINGS_FILTERS: 'RESET_DAILY_SHOOTINGS_FILTERS',
  SAVE_DAILY_SHOOTINGS_PAGINATION: 'SAVE_DAILY_SHOOTINGS_PAGINATION',
  APPEND_DAILY_SHOOTINGS: 'APPEND_DAILY_SHOOTINGS',
  REPLACE_SHOOTING_TOOLTIP: 'REPLACE_SHOOTING_TOOLTIP',
  REMOVE_SHOOTING_TOOLTIP: 'REMOVE_SHOOTING_TOOLTIP',
  UPDATE_CALENDAR_SHOOTING: 'UPDATE_CALENDAR_SHOOTING',
};
