export enum Permission {
  // Organization
  OrganizationUpdate = 'organization.update',
  OrganizationDelete = 'organization.delete',
  // Company
  CompanyCreate = 'company.create',
  CompanyRead = 'company.read',
  CompanyUpdate = 'company.update',
  CompanyDelete = 'company.delete',
  CompanyReport = 'company.report',
  CompanyBalance = 'company.balance',
  // User
  UserCreate = 'user.create',
  UserRead = 'user.read',
  UserUpdate = 'user.update',
  UserDelete = 'user.delete',
  UserAcl = 'user.acl',
  UserReport = 'user.report',
  // Photographer
  PhotographerCreate = 'photographer.create',
  PhotographerRead = 'photographer.read',
  PhotographerUpdate = 'photographer.update',
  PhotographerDelete = 'photographer.delete',
  PhotographerUnavailabilities = 'photographer.unavailabilities',
  PhotographerNameSurnameRead = 'photographer.name-surname.read',
  PhotographerPhoneRead = 'photographer.phone.read',
  PhotographerMailRead = 'photographer.mail.read',
  PhotographerAddressRead = 'photographer.address.read',
  PhotographerIdRead = 'photographer.id.read',
  PhotographerTravelExpensesRead = 'photographer.travel-expenses.read',
  PhotographerGenericInfoRead = 'photographer.generic-info.read',
  PhotographerBalance = 'photographer.balance',
  PhotographerrefundconfigRead = 'photographerrefundconfig.read',
  PhotographerReport = 'photographer.report',
  PhotographerAnalytics = 'photographer.analytics',
  // Pack
  PricingpackageCreate = 'pricingpackage.create',
  PricingpackageRead = 'pricingpackage.read',
  PricingpackageUpdate = 'pricingpackage.update',
  PricingpackageDelete = 'pricingpackage.delete',
  // Shooting (old)
  ShootingCreate = 'shooting.create',
  ShootingRead = 'shooting.read',
  ShootingUpdate = 'shooting.update',
  ShootingManage = 'shooting.manage',
  ShootingEvaluate = 'shooting.evaluate',
  ShootingDownload = 'shooting.download',
  ShootingPhotographer = 'shooting.photographer',
  ShootingCancel = 'shooting.cancel',
  ShootingAcceptPhotos = 'shooting.acceptPhotos',
  ShootingRefusePhotos = 'shooting.refusePhotos',
  ShootingAssign = 'shooting.assign',
  ShootingUnassign = 'shooting.unassign',
  ShootingReport = 'shooting.report',
  ShootingReschedule = 'shooting.reschedule',
  ShootingSchedule = 'shooting.schedule',
  ShootingUpdateEditing = 'shooting.update.editing',
  // Order (new)
  OrderBoInfoRead = 'order.bo-info.read',
  // Invoice item
  InvoiceitemCreate = 'invoiceitem.create',
  InvoiceitemRead = 'invoiceitem.read',
  InvoiceitemDelete = 'invoiceitem.delete',
  // Checklist
  ChecklistCreate = 'checklist.create',
  ChecklistRead = 'checklist.read',
  ChecklistDelete = 'checklist.delete',
  // Authorized Service
  AuthorizedServiceCreate = 'authorizedservice.create',
  AuthorizedServiceRead = 'authorizedservice.read',
  AuthorizedServiceDelete = 'authorizedservice.delete',
  // Company penalty
  CompanyPenaltiesConfigCreate = 'companypenaltiesconfig.create',
  CompanyPenaltiesConfigRead = 'companypenaltiesconfig.read',
  CompanyPenaltiesConfigDelete = 'companypenaltiesconfig.delete',
  // Bulk insert
  BulkCreate = 'bulk.create',
  BulkRead = 'bulk.read',
  BulkDelete = 'bulk.delete',
  // Contact center
  ContactCenterRead = 'contact-center.read',
  ContactCenterUpdate = 'contact-center.update',
  ContactCenterUsersCreate = 'contact-center.users.create',
  ContactCenterUsersRead = 'contact-center.users.read',
  ContactCenterUsersUpdate = 'contact-center.users.update',
  ContactCenterUsersDelete = 'contact-center.users.delete',
  // Payment
  PaymentsSetupcard = 'payments.setupcard',
  PaymentsSubscription = 'payments.subscription',
  PaymentsSubscriptionDelete = 'payments.subscription.delete',
  PaymentsCancelcard = 'payments.cancelcard',
  PaymentsSubscriptionUpdate = 'payments.subscription.update',
  // Feature flag
  FeatureFlagUpdate = 'featureflag.update',
}
