export enum SubscriptionStatus {
  SUBSCRIBED = 'SUBSCRIBED',
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  UNSUBSCRIBED_ACTIVE = 'UNSUBSCRIBED_ACTIVE',
  UNSUBSCRIBED = 'UNSUBSCRIBED',
  UNSUBSCRIBED_GRACE = 'UNSUBSCRIBED_GRACE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}
